import cv2
import numpy as np
from matplotlib import pyplot as plt

arara = cv2.cvtColor(cv2.imread("PDI_Exercicios_3_Imagens/arara.png"), cv2.COLOR_BGR2GRAY)
barra1 = cv2.cvtColor(cv2.imread("PDI_Exercicios_3_Imagens/barra1.png"), cv2.COLOR_BGR2GRAY)
barra2 = cv2.cvtColor(cv2.imread("PDI_Exercicios_3_Imagens/barra2.png"), cv2.COLOR_BGR2GRAY)
barra3 = cv2.cvtColor(cv2.imread("PDI_Exercicios_3_Imagens/barra3.png"), cv2.COLOR_BGR2GRAY)
barra4 = cv2.cvtColor(cv2.imread("PDI_Exercicios_3_Imagens/barra4.png"), cv2.COLOR_BGR2GRAY)
quadrado = cv2.cvtColor(cv2.imread("PDI_Exercicios_3_Imagens/quadrado.png"), cv2.COLOR_BGR2GRAY)
teste = cv2.cvtColor(cv2.imread("PDI_Exercicios_3_Imagens/teste.png"), cv2.COLOR_BGR2GRAY)

arara_dft = cv2.dft(np.float32(arara), flags=cv2.DFT_COMPLEX_OUTPUT)
barra1_dft = cv2.dft(np.float32(barra1), flags=cv2.DFT_COMPLEX_OUTPUT)
barra2_dft = cv2.dft(np.float32(barra2), flags=cv2.DFT_COMPLEX_OUTPUT)
barra3_dft = cv2.dft(np.float32(barra3), flags=cv2.DFT_COMPLEX_OUTPUT)
barra4_dft = cv2.dft(np.float32(barra4), flags=cv2.DFT_COMPLEX_OUTPUT)
quadrado_dft = cv2.dft(np.float32(quadrado), flags=cv2.DFT_COMPLEX_OUTPUT)
teste_dft = cv2.dft(np.float32(teste), flags=cv2.DFT_COMPLEX_OUTPUT)

arara_dft_shift = np.fft.fftshift(arara_dft)
barra1_dft_shift = np.fft.fftshift(barra1_dft)
barra2_dft_shift = np.fft.fftshift(barra2_dft)
barra3_dft_shift = np.fft.fftshift(barra3_dft)
barra4_dft_shift = np.fft.fftshift(barra4_dft)
quadrado_dft_shift = np.fft.fftshift(quadrado_dft)
teste_dft_shift = np.fft.fftshift(teste_dft)

mag_spectrum_arara = 20*np.log(cv2.magnitude(arara_dft_shift[:,:,0], arara_dft_shift[:,:,1]))
mag_spectrum_barra1 = 20*np.log(cv2.magnitude(barra1_dft_shift[:,:,0], barra1_dft_shift[:,:,1]))
mag_spectrum_barra2 = 20*np.log(cv2.magnitude(barra2_dft_shift[:,:,0], barra2_dft_shift[:,:,1]))
mag_spectrum_barra3 = 20*np.log(cv2.magnitude(barra3_dft_shift[:,:,0], barra3_dft_shift[:,:,1]))
mag_spectrum_barra4 = 20*np.log(cv2.magnitude(barra4_dft_shift[:,:,0], barra4_dft_shift[:,:,1]))
mag_spectrum_quadrado = 20*np.log(cv2.magnitude(quadrado_dft_shift[:,:,0], quadrado_dft_shift[:,:,1]) + 1)
mag_spectrum_teste = 20*np.log(cv2.magnitude(teste_dft_shift[:,:,0], teste_dft_shift[:,:,1]))

plt.figure(figsize=(10, 10))
plt.subplot(431)
plt.imshow(mag_spectrum_arara, cmap="gray")
plt.subplot(432)
plt.imshow(mag_spectrum_barra1, cmap="gray")
plt.subplot(433)
plt.imshow(mag_spectrum_barra2, cmap="gray")
plt.subplot(434)
plt.imshow(mag_spectrum_barra3, cmap="gray")
plt.subplot(435)
plt.imshow(mag_spectrum_barra4, cmap="gray")
plt.subplot(436)
plt.imshow(mag_spectrum_quadrado, cmap="gray")
plt.subplot(437)
plt.imshow(mag_spectrum_teste, cmap="gray")
plt.show()
